### ISSUE TITLE
Error pulling SP

### ISSUE THREAD

**Issue by porowns** [KryptedGaming/django-eveonline-connector#50]
```
Task django_eveonline_connector.tasks.update_character_skills[1fec1d46-5b51-49db-acba-b96f3fa268cd] raised unexpected: TypeError("'NoneType' object is not subscriptable",)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django_eveonline_connector/tasks.py", line 287, in update_character_skills
    info.skill_points = response['total_sp']
TypeError: 'NoneType' object is not subscriptable
```

Looks like issue when tranquility is down

**Comment by porowns** [comment]
This error should be suppressed & retried now
