### ISSUE TITLE
Task django_eveonline_connector.tasks.pull_corporation_roster raised unexpected: KeyError('name',)

### ISSUE THREAD

**Issue by porowns** [KryptedGaming/django-eveonline-connector#65]
```
Task django_eveonline_connector.tasks.pull_corporation_roster[b3872ed5-9406-4677-97d4-a21ca8447c30] raised unexpected: KeyError('name',)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/krypted/app/packages/django-eveonline-connector/django_eveonline_connector/tasks.py", line 414, in pull_corporation_roster
    member.update_character_corporation()
  File "/opt/krypted/app/packages/django-eveonline-connector/django_eveonline_connector/models.py", line 414, in update_character_corporation
    external_id=corporation_id)
  File "/opt/krypted/app/packages/django-eveonline-connector/django_eveonline_connector/models.py", line 442, in create_from_external_id
    name=response.data['name'],
KeyError: 'name'
```

**Comment by porowns** [comment]
Pull corporation roster no longer exists.
