### ISSUE TITLE
Failed to resolve IDs

### ISSUE THREAD

**Issue by porowns** [KryptedGaming/django-eveonline-connector#69]
```
Failed to resolve IDs: [0, 98558468, 2117457287, 2113072263, 603976457, 1342819338, 98516874, 2117617943, 434989723, 2115734044, 97234079, 1185432224, 2114345510, 201319079, 1050620328, 98633005, 94921133, 2112658871, 93759298, 96833356, 97226073, 98564576, 2112730977, 175722595, 2112600049, 2112008181, 98079862]

Traceback (most recent call last):
  File "/opt/krypted/app/packages/django-eveonline-connector/django_eveonline_connector/models.py", line 590, in create_from_esi_response
    data, entity_external_id, *args, **kwargs)
  File "/opt/krypted/app/packages/django-eveonline-connector/django_eveonline_connector/models.py", line 834, in _create_from_esi_response
    resolved_ids = resolve_ids_with_types(ids_to_resolve)
  File "/opt/krypted/app/packages/django-eveonline-connector/django_eveonline_connector/utilities/esi/universe.py", line 41, in resolve_ids_with_types
    f"Failed to resolve IDs: {ids_segment}")
django_eveonline_connector.exceptions.EveDataResolutionError: Failed to resolve IDs: [0, 98558468, 2117457287, 2113072263, 603976457, 1342819338, 98516874, 2117617943, 434989723, 2115734044, 97234079, 1185432224, 2114345510, 201319079, 1050620328, 98633005, 94921133, 2112658871, 93759298, 96833356, 97226073, 98564576, 2112730977, 175722595, 2112600049, 2112008181, 98079862]
```

**Comment by porowns** [comment]
Improved logging
